parameters:
   stems.user.min_password_length: 8
   stems.user.max_password_length: false
   stems.user.alphanumeric_password_only: false
   stems.user.password_require_number: false
   stems.user.password_require_symbol: false
   stems.user.password_require_capital: false